/*
 * ecat_conf.h - EtherCAT Library Configuration
 *
 * This file was generated by the Industrial Communication Creator
 * with EtherCAT feature V7.6.0.202512051012
 * from project C:\FACTS_Stuff\Repos\Ecat_Test\glue\ICCTest.iccproj
 * on 2026/03/12 at 16:08:58.
 *
 * @copyright
 * Copyright 2026 NXP
 *
 * NXP Confidential and Proprietary. This software is owned or controlled by NXP
 * and may only be used strictly in accordance with the applicable license
 * terms. By expressly accepting such terms or by downloading, installing,
 * activating and/or otherwise using the software, you are agreeing that you
 * have read, and that you agree to comply with and are bound by, such license
 * terms. If you do not agree to be bound by the applicable license terms, then
 * you may not retain, install, activate or otherwise use the software.
 *
 */

/**
 * \file ecat_conf.h
 * \author port GmbH
 *
 * This module contains the configuration
 * of the EtherCAT Library for the EtherCAT device.
 */



#ifndef ECAT_CONF_H
#define ECAT_CONF_H	1
#define EC_CONFIG_ICCTOOL_VERSION 0x00070600

/* active configuration : 0 */
#define EC_CONFIG_USE_TARGET_0 1


/*
 * General Settings
 */


#define EC_CONFIG_DYN_CFG                   	1
#define EC_CONFIG_EMERGENCY                 	1
#define EC_CONFIG_EMERGENCY_QUEUESIZE       	8
#define EC_CONFIG_PDO_RAM_BUF_SIZE          	128
#define EC_CONFIG_REQUEST_TIMEOUT           	100
#define EC_CONFIG_RESPONSE_TIMEOUT          	1000
#define EC_CONFIG_SDO_INFO                  	1
#define EC_CONFIG_SDO_SEG_BUF_LEN           	1024
#define EC_CONFIG_SEGMENTED_SDO             	1
#define EC_CONFIG_SLAVE                     	1
#define EC_CONFIG_STATE_TIMEOUT_BTOINIT     	5000
#define EC_CONFIG_STATE_TIMEOUT_BTOSAFE     	200
#define EC_CONFIG_STATE_TIMEOUT_INITPREOP   	3000
#define EC_CONFIG_STATE_TIMEOUT_SAFEOP      	10000
#define EC_CONFIG_MAX_OD_ELEMENTS           	10
#define EC_CONFIG_MAX_RPDO_DATA             	1
#define EC_CONFIG_MAX_TPDO_DATA             	1



/*
 * Hardware configuration 0: 0
 */
 

/*
 * CPU Setup
 */
#ifdef EC_CONFIG_USE_TARGET_0

#endif /* EC_CONFIG_USE_TARGET_0*/


/*
 * Compiler Setup
 */
#ifdef EC_CONFIG_USE_TARGET_0

#endif /* EC_CONFIG_USE_TARGET_0 */




/*
 * EtherCAT Services
 */

/* Sync Manager 0 */
#define EC_CONFIG_SM_0_COMM_TYPE 1
#define EC_CONFIG_SM_0_START_ADR 0x1000
#define EC_CONFIG_SM_0_DEFAULT_SIZE 246
#define EC_CONFIG_SM_0_MIN_SIZE 40
#define EC_CONFIG_SM_0_MAX_SIZE 1486
#define EC_CONFIG_SM_0_IRQ_ECAT_EVENT_ENABLED 0
#define EC_CONFIG_SM_0_IRQ_PDI_EVENT_ENABLED 1
#define EC_CONFIG_SM_0_WATCHDOG_ENABLED 0
#define EC_CONFIG_SM_0_ENABLED 1

/* Sync Manager 1 */
#define EC_CONFIG_SM_1_COMM_TYPE 2
#define EC_CONFIG_SM_1_START_ADR 0x1400
#define EC_CONFIG_SM_1_DEFAULT_SIZE 246
#define EC_CONFIG_SM_1_MIN_SIZE 40
#define EC_CONFIG_SM_1_MAX_SIZE 1486
#define EC_CONFIG_SM_1_IRQ_ECAT_EVENT_ENABLED 0
#define EC_CONFIG_SM_1_IRQ_PDI_EVENT_ENABLED 1
#define EC_CONFIG_SM_1_WATCHDOG_ENABLED 0
#define EC_CONFIG_SM_1_ENABLED 1

/* Sync Manager 2 */
#define EC_CONFIG_SM_2_COMM_TYPE 3
#define EC_CONFIG_SM_2_START_ADR 0x1800
#define EC_CONFIG_SM_2_DEFAULT_SIZE 1
#define EC_CONFIG_SM_2_IRQ_ECAT_EVENT_ENABLED 0
#define EC_CONFIG_SM_2_IRQ_PDI_EVENT_ENABLED 1
#define EC_CONFIG_SM_2_WATCHDOG_ENABLED 1
#define EC_CONFIG_SM_2_ENABLED 0

/* Sync Manager 3 */
#define EC_CONFIG_SM_3_COMM_TYPE 4
#define EC_CONFIG_SM_3_START_ADR 0x1C00
#define EC_CONFIG_SM_3_DEFAULT_SIZE 1
#define EC_CONFIG_SM_3_IRQ_ECAT_EVENT_ENABLED 0
#define EC_CONFIG_SM_3_IRQ_PDI_EVENT_ENABLED 1
#define EC_CONFIG_SM_3_WATCHDOG_ENABLED 0
#define EC_CONFIG_SM_3_ENABLED 0


/* Sync Manager general */
/* number of Sync Manager used for the standard receive mailbox */
#define EC_CONFIG_SM_STD_RX_MB 0
/* number of Sync Manager used for the standard send mailbox */
#define EC_CONFIG_SM_STD_TX_MB 1


#define EC_CONFIG_DYN_PDO_MAPPING           	1
#define EC_CONFIG_MAPPING_CNT               	2
#define EC_CONFIG_PDO_CONSUMER              	1
#define EC_CONFIG_PDO_CONS_MAP_CNT          	1
#define EC_CONFIG_PDO_PRODUCER              	1
#define EC_CONFIG_PDO_PROD_MAP_CNT          	1
#define EC_CONFIG_SDO_SERVER                	1

/* 
 * special DEFINE part - don't edit here, it is changed by
 * the Industrial Communication Creator 
 */
#define EC_CONFIG_SPECIAL_START	1


#define EC_CONFIG_SPECIAL_END	1

/* 
 * user specific part - will not be changed by
 * the Industrial Communication Creator
 */
#define EC_CONFIG_USER_SPEC_START	1

#define EC_CONFIG_USER_SPEC_END	1

#endif /* ECAT_CONF_H */
